export enum IpcChannel {
  Config_Get = "config:get",
  Config_Save = "config:save",
  Config_List = "config:list",
  Config_Reset = "config:reset",
  Config_ListProfiles = "config:list-profiles",
  Config_CreateProfile = "config:create-profile",
  Config_SwitchProfile = "config:switch-profile",
  Config_DeleteProfile = "config:delete-profile",

  Scraper_Start = "scraper:start",
  Scraper_Stop = "scraper:stop",
  Scraper_Pause = "scraper:pause",
  Scraper_Resume = "scraper:resume",
  Scraper_GetStatus = "scraper:get-status",
  Scraper_Requeue = "scraper:requeue",
  Scraper_RetryFailed = "scraper:retry-failed",
  Scraper_GetFailedFiles = "scraper:get-failed-files",
  Scraper_HasRecoverableSession = "scraper:has-recoverable-session",
  Scraper_RecoverSession = "scraper:recover-session",

  Crawler_Test = "crawler:test",
  Crawler_ListSites = "crawler:list-sites",

  Network_CheckCookies = "network:check-cookies",

  Translate_TestLlm = "translate:test-llm",
  File_ListEntries = "file:list-entries",
  File_Browse = "file:browse",
  File_Delete = "file:delete",
  File_NfoRead = "file:nfo-read",
  File_NfoWrite = "file:nfo-write",

  Event_Log = "event:log",
  Event_Progress = "event:progress",
  Event_ScrapeResult = "event:scrape-result",
  Event_ScrapeInfo = "event:scrape-info",
  Event_FailedInfo = "event:failed-info",
  Event_ButtonStatus = "event:button-status",
  Event_Shortcut = "event:shortcut",

  App_Info = "app:info",
  App_OpenExternal = "app:open-external",

  Tool_JellyfinActorPhotoSync = "tool:jellyfin-actor-photo-sync",
  Tool_JellyfinActorInfoSync = "tool:jellyfin-actor-info-sync",
  Tool_JellyfinServerCheckConnection = "tool:jellyfin-server-check-connection",
  Tool_EmbyActorPhotoSync = "tool:emby-actor-photo-sync",
  Tool_EmbyActorInfoSync = "tool:emby-actor-info-sync",
  Tool_EmbyServerCheckConnection = "tool:emby-server-check-connection",
  Tool_CreateSymlink = "tool:create-symlink",
  Tool_AmazonPosterScan = "tool:amazon-poster-scan",
  Tool_AmazonPosterLookup = "tool:amazon-poster-lookup",
  Tool_AmazonPosterApply = "tool:amazon-poster-apply",
  Tool_ToggleDevTools = "tool:toggle-devtools",

  Maintenance_Scan = "maintenance:scan",
  Maintenance_Execute = "maintenance:execute",
  Maintenance_Stop = "maintenance:stop",
  Maintenance_GetStatus = "maintenance:get-status",

  Event_MaintenanceItemResult = "event:maintenance-item-result",
}
