/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LogsRouteImport } from "./routes/logs";
import { Route as OverviewRouteImport } from "./routes/overview";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ToolRouteImport } from "./routes/tool";

const OverviewRoute = OverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => rootRouteImport,
} as any);
const ToolRoute = ToolRouteImport.update({
  id: "/tool",
  path: "/tool",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const LogsRoute = LogsRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/logs": typeof LogsRoute;
  "/overview": typeof OverviewRoute;
  "/settings": typeof SettingsRoute;
  "/tool": typeof ToolRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/logs": typeof LogsRoute;
  "/overview": typeof OverviewRoute;
  "/settings": typeof SettingsRoute;
  "/tool": typeof ToolRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/logs": typeof LogsRoute;
  "/overview": typeof OverviewRoute;
  "/settings": typeof SettingsRoute;
  "/tool": typeof ToolRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/logs" | "/overview" | "/settings" | "/tool";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/logs" | "/overview" | "/settings" | "/tool";
  id: "__root__" | "/" | "/about" | "/logs" | "/overview" | "/settings" | "/tool";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  LogsRoute: typeof LogsRoute;
  OverviewRoute: typeof OverviewRoute;
  SettingsRoute: typeof SettingsRoute;
  ToolRoute: typeof ToolRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tool": {
      id: "/tool";
      path: "/tool";
      fullPath: "/tool";
      preLoaderRoute: typeof ToolRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/logs": {
      id: "/logs";
      path: "/logs";
      fullPath: "/logs";
      preLoaderRoute: typeof LogsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/overview": {
      id: "/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof OverviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LogsRoute: LogsRoute,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
  ToolRoute: ToolRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
