name: 上报 Bug
description: 使用中文进行 Bug 报告
labels: ["bug / 缺陷"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
        - label: 我已经搜索了现有的 issues
          required: true
  - type: input
    id: version
    attributes:
      label: MDCz 版本
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 描述你的问题
      description: 简要描述问题，包括复现步骤和期望行为。如有截图请一并附上。
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 相关日志或配置
      description: 日志输出或相关配置片段，注意删除敏感信息。
      render: Text
    validations:
      required: false
